In [69]:
import numpy as np
import matplotlib.pyplot as plt

2(b)

In [73]:
# define the function
def f(x,N):
    return x**2-N

# code to find square root
def square_root(f,x0,N,tol=1e-9):
    for i in range(500):
        x = 1/2 * (x0 + N/x0)
        if(abs(x-x0)/abs(x0)<tol):
            print(f"{i+1} iterations")
            return x
        else:
            x0 = x
    return None

# function call
# N = 121
N = 121
x0 = 1/2*(N+1)
print(f"square root of {N} is {square_root(f,x0,N)}")

print("-----------------------------------------------")

# N = 0.000002
N = 0.000002
x0 = 1/2*(N+1)
print(f"square root of {N} is {square_root(f,x0,N)}")

print("-----------------------------------------------")

# N = 987654321
N = 987654321
x0 = 1/2*(N+1)
print(f"square root of {N} is {square_root(f,x0,N)}")




7 iterations
square root of 121 is 11.0
-----------------------------------------------
13 iterations
square root of 2e-06 is 0.001414213562373095
-----------------------------------------------
19 iterations
square root of 987654321 is 31426.968052931865


2(c)

In [74]:
# Code of Newton's Method
def newton(f, f1, x0, N, tol = 1e-9):
    for i in range(500):
        x = x0 - f(x0,N)/f1(x0)
        if abs(f(x,N)) < tol:
            return f"root at {x:.5f} found in {i + 1} iterations"
        x0 = x
    return f"could not find in {i + 1} iterations, final value: {f(x)} at x = {x:.5f}"

In [75]:
# defining the functions
from math import cos, sin
def f(x,N):
    return x**2-N
def f1(x):
    return 2*x

In [76]:
# function call
# N = 121
N = 121
x0 = 1/2*(N+1)
print(f"square root of {N} is {newton(f,f1,x0,N)}")

# N = 0.000002
N = 0.000002
x0 = 1/2*(N+1)
print(f"square root of {N} is {newton(f,f1,x0,N)}")

# N = 987654321
N = 987654321
x0 = 1/2*(N+1)
print(f"square root of {N} is {newton(f,f1,x0,N)}")

square root of 121 is root at 11.00000 found in 7 iterations
square root of 2e-06 is root at 0.00141 found in 11 iterations
square root of 987654321 is root at 31426.96805 found in 19 iterations


In both the cases, number of iterations are approx. same

In [28]:
print(np.sqrt(121))
print(np.sqrt(0.000002))
print(np.sqrt(987654321))

11.0
0.001414213562373095
31426.968052931865


square root using newton's method and built-in functions are approx same!

# Ques 3

In [30]:
import numpy as np

# Coefficient matrix A and constant vector b
A = np.array([
    [20, 2, -5],
    [5, -20, 2],
    [4, 5, 20],
], dtype=float)

b = np.array([13, 27, 19], dtype=float)
x = np.zeros(len(b))

# Number of iterations
iterations = 25

# Gauss-Jacobi method
for k in range(iterations):
    x_new = np.copy(x)
    
    for i in range(len(A)):
        sum_ = 0
        for j in range(len(A)):
            if i != j:
                sum_ += A[i][j] * x[j]
        
        x_new[i] = (b[i] - sum_) / A[i][i]
    

    x = np.copy(x_new)

# Final result
print("\nFinal solution:")
print(x)


Final solution:
[ 1. -1.  1.]


In [31]:
import numpy as np

# Coefficient matrix A
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
], dtype=float)

b = np.array([6, 15, 24], dtype=float)

x = np.zeros(len(b))

# Number of iterations
iterations = 25

# Gauss-Jacobi method
for k in range(iterations):
    x_new = np.copy(x)
    
    for i in range(len(A)):
        sum_ = 0
        for j in range(len(A)):
            if i != j:
                sum_ += A[i][j] * x[j]
        
        x_new[i] = (b[i] - sum_) / A[i][i]
    
    x = np.copy(x_new)

# Final result
print("\nFinal solution:")
print(x)


Final solution:
[2.59636478e+10 1.40928068e+10 1.27738244e+10]


In [43]:
# Yes, I am able to find out solution for both the cases

In [44]:
# A = D + L + U

In [45]:
import numpy as np

# Function to perform LU decomposition
def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    # Decomposing matrix into Upper and Lower triangular matrices
    for i in range(n):
        # Upper triangular
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += (L[i][j] * U[j][k])
            U[i][k] = A[i][k] - sum

        # Lower triangular
        for k in range(i, n):
            if i == k:
                L[i][i] = 1  # Diagonal as 1
            else:
                sum = 0
                for j in range(i):
                    sum += (L[k][j] * U[j][i])
                L[k][i] = (A[k][i] - sum) / U[i][i]

    return L, U

In [47]:

A = np.array([[20, 2, -5],
              [5, -20, 2],
              [4, 5, 20]], dtype=float)

L, U = lu_decomposition(A)
print("Matrix A:")
print(A)
print("\nLower triangular matrix L:")
print(L)
print("\nUpper triangular matrix U:")
print(U)

D = np.array([[20, 0, 0],
              [0, -20, 0],
              [0, 0, 20]], dtype=float)

print(A)
print(D+L+U)

Matrix A:
[[ 20.   2.  -5.]
 [  5. -20.   2.]
 [  4.   5.  20.]]

Lower triangular matrix L:
[[ 1.          0.          0.        ]
 [ 0.25        1.          0.        ]
 [ 0.2        -0.22439024  1.        ]]

Upper triangular matrix U:
[[ 20.           2.          -5.        ]
 [  0.         -20.5          3.25      ]
 [  0.           0.          21.72926829]]
[[ 20.   2.  -5.]
 [  5. -20.   2.]
 [  4.   5.  20.]]
[[ 41.           2.          -5.        ]
 [  0.25       -39.5          3.25      ]
 [  0.2         -0.22439024  42.72926829]]


In [48]:
Tj = -1*np.linalg.inv(D)@(L+U)
print(Tj)

[[-1.05       -0.1         0.25      ]
 [ 0.0125     -0.975       0.1625    ]
 [-0.01        0.01121951 -1.13646341]]


In [58]:
e_values, e_vectors = np.linalg.eig(Tj)
print(e_values)
print(np.max(abs(e_values)))

[-3.08662415  1.40623141 -0.03071837]
3.086624146656545


In [59]:
import numpy as np

# Function to perform LU decomposition
def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    # Decomposing matrix into Upper and Lower triangular matrices
    for i in range(n):
        # Upper triangular
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += (L[i][j] * U[j][k])
            U[i][k] = A[i][k] - sum

        # Lower triangular
        for k in range(i, n):
            if i == k:
                L[i][i] = 1  # Diagonal as 1
            else:
                sum = 0
                for j in range(i):
                    sum += (L[k][j] * U[j][i])
                L[k][i] = (A[k][i] - sum) / U[i][i]

    return L, U

In [60]:
# Example usage
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)

L, U = lu_decomposition(A)
print("Matrix A:")
print(A)
print("\nLower triangular matrix L:")
print(L)
print("\nUpper triangular matrix U:")
print(U)

D = np.array([[1, 0, 0],
              [0, 5, 0],
              [0, 0, 9]], dtype=float)

print(A)
print(D+L+U)

Matrix A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Lower triangular matrix L:
[[1. 0. 0.]
 [4. 1. 0.]
 [7. 2. 1.]]

Upper triangular matrix U:
[[ 1.  2.  3.]
 [ 0. -3. -6.]
 [ 0.  0.  0.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 3.  2.  3.]
 [ 4.  3. -6.]
 [ 7.  2. 10.]]


In [61]:
Tj = -1*np.linalg.inv(D)@(L+U)
print(Tj)

[[-2.         -2.         -3.        ]
 [-0.8         0.4         1.2       ]
 [-0.77777778 -0.22222222 -0.11111111]]


In [62]:
e_values, e_vectors = np.linalg.eig(Tj)
print(e_values)
print(np.max(abs(e_values)))

[-3.08662415  1.40623141 -0.03071837]
3.086624146656545


### Q4 Soln

In [67]:
# (b)
def g(x,y):
    return 4*y - x**2

def fixed_point(g, x0,y0, tol=1e-6, max_iter=10):
    for _ in range(max_iter):
        x1 = g(x0,y0)  # Update the guess
        
        # Check for convergence
        if abs(x1 - x0) < tol:
            return x1  # Root found

        x0 = x1  # Update the guess for the next iteration

    raise ValueError("Fixed Point Method did not converge within the maximum number of iterations.")

# Example usage
x0= 2  
y0 = 2
tolerance = 1e-6

root = fixed_point(g, x0, y0 ,tol=tolerance)
print('Root =', root)
print('Function value at root =', g(root))

ValueError: Fixed Point Method did not converge within the maximum number of iterations.

In [68]:
# (b)
def g(x,y):
    return 3*y - x - 1

def fixed_point(g, x0,y0, tol=1e-6, max_iter=10):
    for _ in range(max_iter):
        x1 = g(x0,y0)  # Update the guess
        
        # Check for convergence
        if abs(x1 - x0) < tol:
            return x1  # Root found

        x0 = x1  # Update the guess for the next iteration

    raise ValueError("Fixed Point Method did not converge within the maximum number of iterations.")

# Example usage
x0= 2  
y0 = 2
tolerance = 1e-6

root = fixed_point(g, x0, y0 ,tol=tolerance)
print('Root =', root)
print('Function value at root =', g(root))

ValueError: Fixed Point Method did not converge within the maximum number of iterations.