In [1]:
import numpy as np

# Function to perform LU decomposition
def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    # Decomposing matrix into Upper and Lower triangular matrices
    for i in range(n):
        # Upper triangular
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += (L[i][j] * U[j][k])
            U[i][k] = A[i][k] - sum

        # Lower triangular
        for k in range(i, n):
            if i == k:
                L[i][i] = 1  # Diagonal as 1
            else:
                sum = 0
                for j in range(i):
                    sum += (L[k][j] * U[j][i])
                L[k][i] = (A[k][i] - sum) / U[i][i]

    return L, U

# Example usage
A = np.array([[2, -1, -2],
              [-4, 6, 3],
              [-4, -2, 8]], dtype=float)

L, U = lu_decomposition(A)

print("Matrix A:")
print(A)
print("\nLower triangular matrix L:")
print(L)
print("\nUpper triangular matrix U:")
print(U)


Matrix A:
[[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]

Lower triangular matrix L:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]

Upper triangular matrix U:
[[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  3.]]


------------------------
------------------------

Question:
The system of equations is:

                                1x+1y+1z=2
                                6x−4y+5z=31
                                5x+2y+2z=13

In [2]:
### LU Decomposition

import numpy as np

# Function to perform LU decomposition
def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    # Decomposing matrix into Upper and Lower triangular matrices
    for i in range(n):
        # Upper triangular
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += (L[i][j] * U[j][k])
            U[i][k] = A[i][k] - sum

        # Lower triangular
        for k in range(i, n):
            if i == k:
                L[i][i] = 1  # Diagonal as 1
            else:
                sum = 0
                for j in range(i):
                    sum += (L[k][j] * U[j][i])
                L[k][i] = (A[k][i] - sum) / U[i][i]

    return L, U

# Function to perform forward substitution
def forward_substitution(L, b):
    n = len(b)
    y = np.zeros_like(b)

    for i in range(n):
        y[i] = (b[i] - np.dot(L[i, :i], y[:i]))

    return y

# Function to perform back substitution
def back_substitution(U, y):
    n = len(y)
    x = np.zeros_like(y)

    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x

# Example system
A = np.array([[1, 1, 1],
              [6, -4, 5],
              [5, 2, 2]], dtype=float)

b = np.array([2, 31, 13], dtype=float)

# Perform LU decomposition
L, U = lu_decomposition(A)

# Solve Ly = b using forward substitution
y = forward_substitution(L, b)

# Solve Ux = y using back substitution
x = back_substitution(U, y)

print("Solution vector x:")
print(x)


Solution vector x:
[ 3. -2.  1.]


In [4]:
# Gauss Elimination Method

import numpy as np

# Function to perform Gauss elimination
def gauss_elimination(A, b):
    n = len(b)
    
    # Augmenting the matrix A with vector b
    augmented_matrix = np.hstack([A, b.reshape(-1, 1)])

    # Forward elimination to get an upper triangular matrix
    for i in range(n):
        # Pivoting (if necessary)
        max_row = np.argmax(np.abs(augmented_matrix[i:n, i])) + i
        augmented_matrix[[i, max_row]] = augmented_matrix[[max_row, i]]
        
        # Making the diagonal element 1 and eliminating below it
        for j in range(i+1, n):
            factor = augmented_matrix[j, i] / augmented_matrix[i, i]
            augmented_matrix[j, i:] -= factor * augmented_matrix[i, i:]
    
    # Back substitution
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i+1:n], x[i+1:n])) / augmented_matrix[i, i]
    
    return x

# Example system
A = np.array([[1, 1, 1],
              [6, -4, 5],
              [5, 2, 2]], dtype=float)

b = np.array([2, 31, 13], dtype=float)

# Solve using Gauss Elimination
solution = gauss_elimination(A, b)

print("Solution vector x:")
print(solution)


Solution vector x:
[ 3. -2.  1.]
